spring:
  profiles:
    include:
      - oauth
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id:  ab85bef7b29dae05a6a98691be302b07
            redirect-uri: "http://localhost:8086/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: kakao

          naver:
            client-id: xrGWfLq9V8UVs5Tg0N98
            client-secret: CZkbESi8vY
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8086/login/oauth2/code/naver

          google:
            client-id: 272030968540-qqcenqj4v9inlmmnqv8tpc7q4vpjp3dn.apps.googleusercontent.com
            client-secret: abXk4p24pd1YfWtkaSff33xB
            scope:
              - profile
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
